const Products = [
  {
    img: require('../Product/Annamonna1(Fshirt).jpg'),
    name: 'Anna Mona',
    price: 1500,
    discount: 80,
    desc: 'Soft cotton casual shirt with a relaxed everyday fit',
    for: 'Women',
    category: 'Fashion',
    subCategory: 'Shirts',
    type: 'Casuals',
    rating: 4.2,
  },
  {
    img: require('../Product/BlueRonin1(Fshirt).jpg'),
    name: 'Blue Ronin',
    price: 2000,
    discount: 60,
    desc: 'Stylish formal shirt designed for office and outings',
    for: 'Women',
    rating: 4.4,
    category: 'Fashion',
    subCategory: 'Shirts',
    type: 'Formals',
  },
  {
    img: require('../Product/Grecilooks1(Fshirt).jpg'),
    name: 'Greci Looks',
    price: 800,
    discount: 15,
    desc: 'Lightweight formal wear with breathable fabric',
    for: 'Women',
    rating: 4.1,
    category: 'Fashion',
    subCategory: 'Shirts',
    type: 'Formals',
  },
  {
    img: require('../Product/Litzo1(Fshirt).jpg'),
    name: 'LITZO',
    price: 1200,
    discount: 5,
    desc: 'Minimalist design shirt for a clean elegant look',
    for: 'Women',
    rating: 4.7,
    category: 'Fashion',
    subCategory: 'Shirts',
    type: 'Casuals',
  },
  {
    img: require('../Product/Uspolo1(Fshirt).jpg'),
    name: 'US Polo',
    price: 500,
    discount: 5,
    desc: 'Comfort-fit casual shirt for daily wear',
    for: 'Women',
    rating: 3.9,
    category: 'Fashion',
    subCategory: 'Shirts',
    type: 'Casuals',
  },
  {
    img: require('../Product/VanHeusen1(Fshirt).jpg'),
    name: 'Van Heusen',
    price: 2000,
    discount: 10,
    desc: 'Premium formal shirt with a modern silhouette',
    for: 'Women',
    rating: 4.9,
    category: 'Fashion',
    subCategory: 'Shirts',
    type: 'Formals',
  },
  {
    img: require('../Product/Finivo1(Mshirt).jpg'),
    name: 'FINIVO',
    price: 1500,
    discount: 20,
    desc: 'Solid cotton formal shirt with full sleeves and regular fit',
    for: 'Men',
    rating: 4.2,
    category: 'Fashion',
    subCategory: 'Shirts',
    type: 'Casuals',
  },
  {
    img: require('../Product/IndianGarage1(Mshirt).jpg'),
    name: 'Indian Garage',
    price: 1400,
    discount: 25,
    desc: 'Trendy slim-fit shirt perfect for casual occasions',
    for: 'Men',
    rating: 4.3,
   category: 'Fashion',
    subCategory: 'Shirts',
    type: 'Casuals',
  },
  {
    img: require('../Product/IndianGarage2(Mshirt).jpg'),
    name: 'Indian Garage',
    price: 1600,
    discount: 30,
    desc: 'Checked casual shirt with a youthful street style',
    for: 'Men',
    rating: 4.1,
    category: 'Fashion',
    subCategory: 'Shirts',
    type: 'Casuals',
  },
  {
    img: require('../Product/MajesticMan1(Mshirt).jpg'),
    name: 'Majestic Man',
    price: 1800,
    discount: 35,
    desc: 'Classic formal shirt with sharp tailoring',
    for: 'Men',
    rating: 4.5,
    category: 'Fashion',
    subCategory: 'Shirts',
    type: 'Formals',
  },
  {
    img: require('../Product/USPolo1(Mshirt).jpg'),
    name: 'US Polo',
    price: 2200,
    discount: 15,
    desc: 'Premium branded shirt with long-lasting comfort',
    for: 'Men',
    rating: 4.6,
    category: 'Fashion',
    subCategory: 'Shirts',
    type: 'Formals',
  },
  {
    img: require('../Product/UTurn1(Mshirt).jpg'),
    name: 'UTurn',
    price: 1100,
    discount: 40,
    desc: 'Casual cotton shirt designed for all-day wear',
    for: 'Men',
    rating: 4.0,
    category: 'Fashion',
    subCategory: 'Shirts',
    type: 'Formals',
  },
  {
    img:require('../Product/Campus1(Msportshoe).jpg'),
    name:'Campus',
    price:1699,
    discount:43,
    desc:'Campus Men Hurricane Running Shoes',
    for:'Men',
    rating:4.2,
    category: 'Fashion',
    subCategory: 'Shoes',
    type:'Sports'
  },
  {
    img:require('../Product/BRUTON1(Msportshoe).jpg'),
    name:'BRUTON',
    price:2499,
    discount:73,
    desc:'BRUTON EVA Lite Sport Shoes Running Shoes for Men- Blue',
    for:'Men',
    rating:3.9,
    category: 'Fashion',
    subCategory: 'Shoes',
    type:'Sports'
  },
  {
    img:require('../Product/ASIAN1(Msportshoe).jpg'),
    name:'ASIAN',
    price:999,
    discount:40,
    desc:'ASIAN Men Lace Up Running Shoes',
    for:'Men',
    rating:4.0,
    category: 'Fashion',
    subCategory: 'Shoes',
    type:'Sports'
  },
  {
    img:require('../Product/LANCER(Msportshoes).jpg'),
    name:'LANCER',
    price:1249,
    discount:58,
    desc:'Mens Indus-251 Running Shoe',
    for:'Men',
    rating:4.2,
    category: 'Fashion',
    subCategory: 'Shoes',
    type:'Sports'
  },
  {
    img:require('../Product/BRUTON2(Msportshoes).jpg'),
    name:'BRUTON',
    price:1299,
    discount:78,
    desc:`BRUTON Exclusive Trendy Sports Running Shoes | Casual Shoe | Sneakers for Men's & Boy's'`,
    for:'Men',
    rating:4.2,
    category: 'Fashion',
    subCategory: 'Shoes',
    type:'Sports'
  },
  {
    img:require('../Product/Campus2(Msportshoe).jpg'),
    name:'Campus',
    price:2299,
    discount:45,
    desc:'Campus Men Terminator (N) Running Shoes',
    for:'Men',
    rating:4.0,
    category: 'Fashion',
    subCategory: 'Shoes',
    type:'Sports'
  },
  {
    img:require('../Product/SPARX1(Fsportshoe).jpg'),
    name:'SPARX',
    price:1049,
    discount:17,
    desc:'Women Sx0167L Sneaker',
    for:'Women',
    rating:4.2,
    category: 'Fashion',
    subCategory: 'Shoes',
    type:'Sports'
  },
  {
    img:require('../Product/SPARX2(Fsportshoe).jpg'),
    name:'SPARX',
    price:949,
    discount:30,
    desc:'Women SL 168 Walking Shoe',
    for:'Women',
    rating:4.1,
    category: 'Fashion',
    subCategory: 'Shoes',
    type:'Sports'
  },
  {
    img:require('../Product/ASIAN1(Fsportshoe).jpg'),
    name:'ASIAN',
    price:1049,
    discount:30,
    desc:`Women's Cute Sports Running Shoes,Walking, Gym Casual Sneaker Lace-Up Shoes for Girl's`,
    for:'Women',
    rating:4.0,
    category: 'Fashion',
    subCategory: 'Shoes',
    type:'Sports'
  },
  {
    img:require('../Product/ASIAN2(Fsportshoe).jpg'),
    name:'ASIAN',
    price:1499,
    discount:53,
    desc:`Women's FIREFLY-09 Sports Running,Walking,Gym Shoes with Max Cushion Technology Lightweight Eva Sole with Memory Foam`,
    for:'Women',
    rating:4.1,
    category: 'Fashion',
    subCategory: 'Shoes',
    type:'Sports'
  },
  {
    img:require('../Product/ASIAN3(Fsportshoe).jpg'),
    name:'ASIAN',
    price:799,
    discount:18,
    desc:`Women's Cute Sports Running Shoes,Walking, Gym Casual Sneaker Lace-Up Shoes for Girl's`,
    for:'Women',
    rating:4.0,
    category: 'Fashion',
    subCategory: 'Shoes',
    type:'Sports'
  },
  {
    img:require('../Product/ATHCO1(Fsportshoe).jpg'),
    name:'ATHCO',
    price:2999,
    discount:75,
    desc:`Womens Kia Memory Foam Comfort Shoes|Running|Walking|Sneaker`,
    for:'Women',
    rating:4.5,
    category: 'Fashion',
    subCategory: 'Shoes',
    type:'Sports'
  },

  
  


];

export { Products };
